import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

import { log, kbHeader } from '../logger';
import { callCopilot } from '../utils/copilot';
import { scanProject } from '../utils/project-scanner';
import { KB_STEPS } from '../constants/kb-steps';

export async function generateKnowledgeBase(
  workspaceRoot: string,
  model: vscode.LanguageModelChat,
  token: vscode.CancellationToken,
  progress: vscode.Progress<{ message?: string; increment?: number }>,
  extensionPath: string
): Promise<void> {

  const cfg       = vscode.workspace.getConfiguration('autoSpecKit');
  const kbRelPath = cfg.get<string>('knowledgeBasePath', 'knowledge-base');
  const kbPath    = path.join(workspaceRoot, kbRelPath);

  // ── Check existing KB ──────────────────────────────────────────
  if (fs.existsSync(kbPath)) {
    const existingFiles = fs.readdirSync(kbPath).filter(f => f.endsWith('.md'));
    if (existingFiles.length > 0) {
      const choice = await vscode.window.showQuickPick(
        [
          { label: `🔄 Regenerate KB (overwrite ${existingFiles.length} existing files)`, overwrite: true },
          { label: '❌ Cancel — Keep existing KB', overwrite: false },
        ],
        {
          title: '⚠️ Knowledge Base already exists!',
          placeHolder: `${kbRelPath}/ already has ${existingFiles.length} files. Regenerate from scratch?`,
        }
      );
      if (!choice?.overwrite) {
        log('⏭  Knowledge Base generation cancelled (KB already exists).');
        return;
      }
    }
  }

  // ── Create KB directory ────────────────────────────────────────
  fs.mkdirSync(kbPath, { recursive: true });

  const ch = (await import('../logger')).getChannel();
  ch.appendLine('');
  ch.appendLine('╔═══════════════════════════════════════════════════════════════╗');
  ch.appendLine('║       📚  AUTO SPEC KIT — GENERATE KNOWLEDGE BASE            ║');
  ch.appendLine('╚═══════════════════════════════════════════════════════════════╝');
  ch.appendLine(`\nWorkspace : ${workspaceRoot}`);
  ch.appendLine(`KB Path   : ${kbPath}`);
  ch.appendLine(`Model     : ${model.name}\n`);

  // ── Scan project ───────────────────────────────────────────────
  log('📂 Scanning project files...');
  progress.report({ message: 'Scanning project...', increment: 5 });
  const projectScan = scanProject(workspaceRoot);

  // Save scan for transparency / debugging
  fs.writeFileSync(
    path.join(kbPath, '_project-scan.md'),
    `# Project Scan\n_Auto-generated by Auto Spec Kit — do not edit_\n\n${projectScan}`,
    'utf-8'
  );
  log('✅ Project scan saved to _project-scan.md');

  // ── System context for ALL KB steps ───────────────────────────
  const KB_SYSTEM = `\
You are a Principal Software Engineer and Business Analyst hired to deeply understand this codebase.

Your mission is NOT just to describe the code — but to understand WHY the code exists and WHAT PROBLEM IT SOLVES.

=== PROJECT FILES ===
${projectScan}

=== ANALYSIS METHOD ===
For every file you read, ask yourself:
- What business domain does this class/function/variable name suggest?
- What business rule is being enforced here?
- Is this a happy path or an edge case?
- Who (which user role) calls this and for what purpose?
- If this code were deleted, how would the business be affected?

=== HOW TO READ CODE TO UNDERSTAND BUSINESS ===
- Read Entity/Model names → infer domain concepts
- Read Enum values → infer business states
- Read validation/guard/if-else → infer business rules
- Read test cases → infer important business scenarios
- Read error messages → infer business constraints
- Read constants/config → infer business parameters
- Read comments/docstrings → extract original business intent
- Read migration files → infer business evolution over time

=== MANDATORY REQUIREMENTS ===
1. ALWAYS cite actual file paths + function/class/variable names as evidence
   Wrong: "This module handles payment"
   Right: "PaymentService.processCheckout() [src/payment/payment.service.ts:45] handles payment by..."

2. Do NOT write generic statements — if no evidence is found in the files, write "not found in codebase"
   Wrong: "The system has authentication features"
   Right: "JWT auth via AuthGuard [src/auth/auth.guard.ts] + RefreshToken entity [src/auth/entities/refresh-token.entity.ts]"

3. Write all explanations in English. Keep code/identifiers/paths in their original form.

4. Analyze at BUSINESS DEPTH — don't just describe technical structure, explain:
   - What user problem does this feature exist to solve?
   - What business rule is being implemented?
   - What edge cases have been handled?
   - Which code areas are most critical and why?

5. Prioritize analysis in this order: test files > service layer > controller > model
   (Test files usually reveal business intent most accurately)

6. When you see magic numbers (5000, 30, 'active', 'pending'...) → explain their business meaning`;

  const ai = (prompt: string, label: string) =>
    callCopilot(model, KB_SYSTEM, prompt, token, label);

  const total = KB_STEPS.length + 1; // +1 for review-skills.md (final step)
  const inc   = Math.floor(90 / total);

  // ── Run each KB step (steps 1–15) ─────────────────────────────
  for (let i = 0; i < KB_STEPS.length; i++) {
    if (token.isCancellationRequested) {
      log('\n⚠  Knowledge Base generation cancelled by user.');
      return;
    }

    const step = KB_STEPS[i];

    kbHeader(i + 1, total, step.label);
    progress.report({ message: `KB ${i + 1}/${total}: ${step.label}`, increment: inc });

    const content = await ai(step.prompt, step.label);

    const outPath = path.join(kbPath, step.file);
    fs.writeFileSync(outPath, content, 'utf-8');
    log(`\n✅ Saved → ${kbRelPath}/${step.file}  (${(content.length / 1024).toFixed(1)}KB)`);
  }

  // ══════════════════════════════════════════════════════════════
  // FINAL KB STEP — Review Skills (Universal Template + Section 14)
  // ══════════════════════════════════════════════════════════════
  if (!token.isCancellationRequested) {
    const reviewStep = KB_STEPS.length + 1;
    kbHeader(reviewStep, total, 'Review Skills (Universal + Project-Specific)');
    progress.report({ message: `KB ${reviewStep}/${total}: Review Skills — merging universal template...`, increment: inc });

    // ── Load Universal Template from resources/ ───────────────────
    const templatePath = path.join(extensionPath, 'resources', 'review-skills-universal.md');
    let universalTemplate = '';
    if (fs.existsSync(templatePath)) {
      universalTemplate = fs.readFileSync(templatePath, 'utf-8');
      log(`✅ Universal review template loaded (${(universalTemplate.length / 1024).toFixed(1)}KB)`);
    } else {
      log(`⚠  resources/review-skills-universal.md not found at: ${templatePath}`);
      log(`   → Will generate review-skills.md from scratch via Copilot (fallback)`);
    }

    // ── Copilot only generates Section 14 — Project-Specific Rules ──
    log(`\nℹ  Copilot analyzing codebase to generate Section 14 (Project-Specific Rules)...`);
    const section14Prompt = `\
Based on the PROJECT FILES analyzed, fill in the content for **Section 14 — PROJECT-SPECIFIC RULES**.

Goal: Find rules SPECIFIC to this project that are NOT covered by the general ruleset.
Do not repeat what is already covered by general rules (Security, Architecture, Performance...).

**Content requirements:**
- Every rule must have a real example CITED from the codebase (file path, function name, specific pattern).
- Severity: [CRITICAL], [MAJOR], or [MINOR].
- If the project has no specific rules, write "(no project-specific rules found)" instead of making them up.

**Return EXACTLY this format — no extra headers, no markdown wrapping:**

### Project-Specific Naming Conventions
- (real example from codebase or "(none found)")

### Project-Specific Architecture / Layer Rules
- (real example from codebase or "(none found)")

### Mandatory Patterns & Conventions in this Project
- (real example from codebase or "(none found)")

### Anti-Patterns Banned in this Project
- (real example from codebase or "(none found)")

### Business Rules to Enforce in Every New Feature
- (real example from codebase or "(none found)")

### Project-Specific Technologies / Libraries and Correct Usage
- (real example from codebase or "(none found)")`;

    const section14Content = await ai(section14Prompt, 'Review Skills — Section 14');

    // ── Merge universal template + Section 14 ─────────────────────
    let reviewSkillsContent: string;
    const PLACEHOLDER = '<!-- Placeholder — will be automatically updated by Auto Spec Kit final KB step -->';

    if (universalTemplate) {
      if (universalTemplate.includes(PLACEHOLDER)) {
        reviewSkillsContent = universalTemplate.replace(PLACEHOLDER, section14Content);
        log(`✅ Section 14 merged into Universal Template`);
      } else {
        reviewSkillsContent = universalTemplate + '\n\n' + section14Content;
        log(`⚠  Placeholder not found — Section 14 appended to end of template`);
      }
    } else {
      reviewSkillsContent =
        `# Review Skills — Project-Specific Rules\n\n` +
        `> ⚠️ Universal template could not be loaded. These are project-specific rules only.\n` +
        `> For the full review skill, copy resources/review-skills-universal.md into knowledge-base/.\n\n` +
        section14Content;
    }

    const rsOutPath = path.join(kbPath, 'review-skills.md');
    fs.writeFileSync(rsOutPath, reviewSkillsContent, 'utf-8');
    log(`✅ Saved → ${kbRelPath}/review-skills.md  (${(reviewSkillsContent.length / 1024).toFixed(1)}KB)`);
    log(`   ${total} sections = ${total - 1} universal rules + 1 project-specific section`);
  }

  // ── Summary ────────────────────────────────────────────────────
  const ch2 = (await import('../logger')).getChannel();
  ch2.appendLine('');
  ch2.appendLine('╔═══════════════════════════════════════════════════════════════╗');
  ch2.appendLine('║         ✅  KNOWLEDGE BASE GENERATION COMPLETE!              ║');
  ch2.appendLine('╚═══════════════════════════════════════════════════════════════╝');
  log(`\n✅ ${total} files generated in: ${kbPath}`);
  log(`\n🌟 Most important files:`);
  log(`   → ${kbRelPath}/13-business-rules.md   — all business rules & invariants`);
  log(`   → ${kbRelPath}/10-core-flows.md        — core business flows`);
  log(`   → ${kbRelPath}/review-skills.md        — injected into every code review`);
  log(`\n💡 Next step: Run a task with Ctrl+Shift+K to start using the Knowledge Base.`);

  const rsPath = path.join(kbPath, 'review-skills.md');
  if (fs.existsSync(rsPath)) {
    const doc = await vscode.workspace.openTextDocument(rsPath);
    await vscode.window.showTextDocument(doc, { preview: false });
  }

  vscode.commands.executeCommand('workbench.files.action.refreshFilesExplorer');

  const action = await vscode.window.showInformationMessage(
    `📚 Knowledge Base generated! ${total} files in ${kbRelPath}/`,
    'Open KB Folder',
    'Run a task now'
  );
  if (action === 'Open KB Folder') {
    vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file(kbPath));
  } else if (action === 'Run a task now') {
    vscode.commands.executeCommand('autoSpecKit.run');
  }
}
