/**
 * write-document.ts — Investigate & Document (Business ↔ Code mapping)
 *
 * Produces a precise technical document for a feature/entity/module that maps
 * BUSINESS concepts to CODE at the field level, grounded in the KB + real source.
 * Exports a self-contained HTML file (and a Markdown copy) and opens a webview.
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

import { log, banner } from '../logger';
import { callCopilot } from '../utils/copilot';
import {
  selectKBTopicsForQuestion,
  loadKBForTopics,
  loadMatchingModuleDocs,
  SmartContextLoader,
} from '../utils/smart-context';
import { buildDocumentHtml } from '../utils/html-builder';

export interface WriteDocumentResult {
  markdown: string;
  htmlFile: string;
  mdFile: string;
}

export async function writeDocument(
  topic: string,
  workspaceRoot: string,
  model: vscode.LanguageModelChat,
  token: vscode.CancellationToken,
): Promise<WriteDocumentResult> {
  const cfg = vscode.workspace.getConfiguration('autoSpecKit');
  const kbRelPath = cfg.get<string>('knowledgeBasePath', 'knowledge-base');
  const sessionsDir = cfg.get<string>('sessionsDir', 'spec-kit-sessions');

  banner(['📝 WRITE DOCUMENT', `Topic: ${topic.slice(0, 60)}`]);
  log(`ℹ  Topic: ${topic}\n`);

  // ── 1. Knowledge-base context (topic + always business/domain/architecture) ──
  const topics = [...new Set([...selectKBTopicsForQuestion(topic), 'domain', 'business-rules', 'architecture'])];
  const kb = loadKBForTopics(workspaceRoot, kbRelPath, topics, 20_000);
  const moduleDocs = loadMatchingModuleDocs(workspaceRoot, kbRelPath, topic, 16_000);

  // ── 2. Relevant source code (field-level grounding) ──
  let sourceCtx = '';
  try {
    const loader = new SmartContextLoader();
    const { files, kbTopics } = await loader.discoverRelevantContext(topic, workspaceRoot, kbRelPath, model, token);
    const smart = loader.loadContext(workspaceRoot, kbRelPath, files, kbTopics, 50_000);
    sourceCtx = loader.buildAgentContext(smart.chunks, ['source'], undefined, 30_000);
  } catch {
    log('⚠  Source discovery failed — documenting from KB only');
  }

  const SYSTEM = `You are a senior business analyst AND software engineer producing precise technical documentation that maps BUSINESS to CODE at the FIELD level.
Use ONLY the provided context. Cite real file paths, class/function names and field names. If something is not in the context, write "(not found in codebase)" — never invent.
Output GitHub-Flavored Markdown with proper tables.`;

  const prompt = `Write a complete, accurate technical document for: "${topic}".

Follow this exact structure (Markdown; use TABLES for all mappings):

# <Clear document title>
_Scope: ${topic} · generated by Auto Spec Kit_

## 1. Business Overview
What this does, who uses it, and the business value/problem it solves.

## 2. Business ↔ Code Field Mapping
For EACH relevant entity/model/DTO, output a table covering every important field:

| Field | Type | Business Meaning | Validation / Business Rule | Source (file · class.field / DB column) |
|-------|------|------------------|----------------------------|------------------------------------------|

Be exhaustive and cite real names.

## 3. Business Flows (mapped to code)
Step-by-step. For each step, name the file + function that implements it.

## 4. Business Rules & Invariants
| Rule | Where enforced (file · function) | Severity |
|------|----------------------------------|----------|

## 5. API / Entry Points (if any)
| Method | Path | Purpose | Auth |
|--------|------|---------|------|

## 6. Assumptions & Gaps
List anything inferred, ambiguous, or "(not found in codebase)".

=== KNOWLEDGE BASE (relevant subset) ===
${kb || '(no knowledge base — run Scan Project first for best results)'}
${moduleDocs ? `\n=== MODULE DOCS ===\n${moduleDocs}` : ''}
${sourceCtx ? `\n=== RELEVANT SOURCE CODE ===\n${sourceCtx}` : ''}`;

  const markdown = await callCopilot(model, SYSTEM, prompt, token, 'Write Document');

  // ── 3. Save Markdown + HTML ──
  const outDir = path.join(workspaceRoot, sessionsDir, 'documents');
  fs.mkdirSync(outDir, { recursive: true });
  const slug = (topic.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 50)) || 'document';
  const ts = new Date().toISOString().slice(0, 10);
  const mdFile = path.join(outDir, `${slug}-${ts}.md`);
  const htmlFile = path.join(outDir, `${slug}-${ts}.html`);

  fs.writeFileSync(mdFile, markdown, 'utf-8');
  const html = buildDocumentHtml(topic, markdown);
  fs.writeFileSync(htmlFile, html, 'utf-8');
  log(`✅ Document saved: ${path.relative(workspaceRoot, htmlFile)}`);

  // ── 4. Open as a (static, no-script) webview + offer browser ──
  const panel = vscode.window.createWebviewPanel(
    'autoSpecKitDoc',
    `📝 ${topic.slice(0, 40)}`,
    vscode.ViewColumn.One,
    { enableScripts: false, retainContextWhenHidden: true, localResourceRoots: [] },
  );
  panel.webview.html = html;

  vscode.window.showInformationMessage(
    `📝 Document generated: ${path.basename(htmlFile)}`,
    'Open HTML in Browser',
  ).then(choice => {
    if (choice === 'Open HTML in Browser') {
      vscode.env.openExternal(vscode.Uri.file(htmlFile));
    }
  });

  vscode.commands.executeCommand('workbench.files.action.refreshFilesExplorer');

  return { markdown, htmlFile, mdFile };
}
