/**
 * Step 04 — Code Generation (Multi-Agent)
 *
 * Uses file discovery data from Step 01 to split code generation:
 *   1. Reads which modules/files need to be created/modified from the plan
 *   2. Spawns parallel code generators — one per module/layer
 *   3. A merge agent assembles and resolves cross-module dependencies
 *
 * Falls back to single-agent if plan doesn't have enough structure to split.
 */

import { log } from '../../../logger';
import { callCopilot } from '../../../utils/copilot';
import { saveFile, loadKbDocs } from '../../../utils/file-utils';
import { AgentOrchestrator, SubAgent, orchestratorConfigFor } from '../../../utils/agent-orchestrator';
import { SmartContextLoader } from '../../../utils/smart-context';
import { PipelineContext, PipelineStep, StepResult } from '../types';

export class Step04CodeGeneration implements PipelineStep {
  readonly id = 'step-04';
  readonly name = 'Code Generation (Multi-Agent)';
  readonly activeLabel = 'Generating code with parallel agents...';

  async execute(ctx: PipelineContext): Promise<StepResult> {
    const planFinal = ctx.stepOutputs.get('step-03')?.output ?? '';

    // Try to split the plan into parallelizable work units
    const workUnits = this.extractWorkUnits(planFinal);

    if (workUnits.length <= 1) {
      // Plan is too simple or couldn't be split — use single agent
      return this.singleAgentGenerate(ctx, planFinal);
    }

    // Load relevant source files for reference
    const relevantFiles = ctx.stepOutputs.get('step-01')?.data?.relevantFiles as string[] ?? [];
    const loader = new SmartContextLoader();
    const smartCtx = loader.loadContext(ctx.workspaceRoot, ctx.kbRelPath, relevantFiles, ['conventions'], 30_000);
    const referenceCode = loader.buildAgentContext(smartCtx.chunks, ['source', 'kb'], ['conventions'], 15_000);

    // Architecture guardrails: the documented patterns + conventions new code MUST follow.
    const archGuardrails = loadKbDocs(
      ctx.workspaceRoot, ctx.kbRelPath,
      ['16-architecture-patterns.md', '12-conventions.md'], 14_000,
    );
    const archBlock = archGuardrails
      ? `\n\n=== ARCHITECTURE & DESIGN PATTERNS (MUST FOLLOW — DO NOT BREAK) ===\n${archGuardrails}`
      : '';

    // Spawn parallel code generators
    const orchestrator = new AgentOrchestrator(orchestratorConfigFor(ctx, 'generative', 3));

    const agents: SubAgent[] = workUnits.map((unit, i) => ({
      id: `codegen-${i}`,
      role: `Code Generator: ${unit.label}`,
      priority: unit.priority,
      systemContext: `${ctx.systemPrompt}\n\n=== REFERENCE CODE (existing patterns) ===\n${referenceCode}${archBlock}`,
      prompt: `\
## FULL REQUIREMENT
${ctx.requirement}

## YOUR ASSIGNMENT — ${unit.label}
${unit.description}

## FILES TO CREATE/MODIFY
${unit.files.map(f => `- ${f}`).join('\n')}

## FULL PLAN CONTEXT
${planFinal}

## INSTRUCTIONS
1. Implement ONLY the files listed in "YOUR ASSIGNMENT". Do NOT implement other files.
2. Use ### FILE: <path> format for each file.
3. Write complete, production-ready code — NO placeholders.
4. Follow existing project patterns exactly (see REFERENCE CODE).
5. ARCHITECTURE: follow the documented design pattern of the target module and respect the layer/dependency rules and "Architecture Invariants — DO NOT BREAK". Do NOT cross layer boundaries (e.g. controller calling the DB directly) or introduce a different pattern than the surrounding module. When in doubt, copy the matching Extension Recipe.
6. Include proper imports, types, error handling.
7. Language: ${ctx.lang}`,
    }));

    const mergeInstruction = `\
You are assembling code from ${workUnits.length} parallel code generators into a single coherent output.

## RULES
1. Keep ALL ### FILE: prefixes — do NOT rename or merge files.
2. If multiple agents generated the same file, merge the content intelligently.
3. Ensure imports between files are correct.
4. Verify no duplicate function/class names across files.
5. Output format: one ### FILE: block per file, in dependency order (base → dependent).
6. Language: ${ctx.lang}`;

    const { merged, agentResults } = await orchestrator.runAndMerge(
      agents, mergeInstruction, ctx.model, ctx.token, ctx.systemPrompt,
    );

    let code = merged;
    if (!code.trim()) {
      log(`⚠  Multi-agent codegen failed — falling back to single agent`);
      return this.singleAgentGenerate(ctx, planFinal);
    }

    saveFile(ctx.sessionDir, '03-code/code-raw.md', code);

    for (const result of agentResults) {
      if (result.success && result.output) {
        saveFile(ctx.sessionDir, `03-code/agent-${result.agentId}.md`, result.output);
      }
    }

    log(`✅ Code generated by ${agentResults.filter(r => r.success).length} parallel agents`);
    return { output: code };
  }

  // ─── Helpers ────────────────────────────────────────────────────

  private async singleAgentGenerate(ctx: PipelineContext, plan: string): Promise<StepResult> {
    log(`ℹ  Using single-agent code generation`);

    const archGuardrails = loadKbDocs(
      ctx.workspaceRoot, ctx.kbRelPath,
      ['16-architecture-patterns.md', '12-conventions.md'], 14_000,
    );
    const sys = archGuardrails
      ? `${ctx.systemPrompt}\n\n=== ARCHITECTURE & DESIGN PATTERNS (MUST FOLLOW — DO NOT BREAK) ===\n${archGuardrails}`
      : ctx.systemPrompt;

    const code = await callCopilot(ctx.model, sys, `\
Implement ALL code for the following requirement based on the approved plan.

## REQUIREMENT: ${ctx.requirement}

## APPROVED PLAN:
${plan}

## FORMAT for each file:
### FILE: src/path/to/file.${ctx.lang === 'typescript' ? 'ts' : ctx.lang === 'python' ? 'py' : ctx.lang}
\`\`\`${ctx.lang}
// code
\`\`\`

## RULES:
- Complete, production-ready code — NO placeholders.
- Follow exact conventions from the knowledge base.
- ARCHITECTURE: follow the documented design pattern of the target module; respect layer/dependency rules and the "Architecture Invariants — DO NOT BREAK"; do not introduce a different pattern or cross layer boundaries.
- Language: ${ctx.lang}`, ctx.token, 'Code Generation');

    saveFile(ctx.sessionDir, '03-code/code-raw.md', code);
    log(`✅ Code saved to 03-code/code-raw.md`);
    return { output: code };
  }

  /**
   * Extract parallelizable work units from the plan.
   * Looks for file groupings, module boundaries, or numbered steps.
   */
  private extractWorkUnits(plan: string): WorkUnit[] {
    const units: WorkUnit[] = [];

    // Strategy 1: Find "Files to CREATE" / "Files to MODIFY" sections
    const filePattern = /(?:create|modify|new file|change).*?[`"]?([^\s`"]+\.\w{2,4})[`"]?/gi;
    const allFiles: string[] = [];
    let match: RegExpExecArray | null;
    while ((match = filePattern.exec(plan)) !== null) {
      const file = match[1].trim();
      if (file.includes('/') && !allFiles.includes(file)) {
        allFiles.push(file);
      }
    }

    if (allFiles.length < 3) {
      // Not enough files to split meaningfully
      return [];
    }

    // Group files by directory (module boundary)
    const groups = new Map<string, string[]>();
    for (const file of allFiles) {
      const parts = file.split('/');
      // Use first 2 levels as group key (e.g., "src/modules/orders")
      const groupKey = parts.length > 2 ? parts.slice(0, 3).join('/') : parts.slice(0, 2).join('/');
      if (!groups.has(groupKey)) { groups.set(groupKey, []); }
      groups.get(groupKey)!.push(file);
    }

    if (groups.size <= 1) {
      return []; // All in one module — not worth splitting
    }

    let priority = groups.size;
    for (const [groupKey, files] of groups) {
      units.push({
        label: groupKey,
        description: `Generate/modify files in ${groupKey}`,
        files,
        priority: priority--,
      });
    }

    log(`ℹ  Plan split into ${units.length} work units: ${units.map(u => u.label).join(', ')}`);
    return units;
  }
}

interface WorkUnit {
  label: string;
  description: string;
  files: string[];
  priority: number;
}
